
/**
 * NotificationType
 * 
 * @description 
 * - 
 */
export const NotificationType = {
  // 그래프 생성 요청 관련
  GRAPH_GENERATION_REQUESTED: 'GRAPH_GENERATION_REQUESTED',
  GRAPH_GENERATION_REQUEST_FAILED: 'GRAPH_GENERATION_REQUEST_FAILED',

  // 그래프 생성 결과 관련
  GRAPH_GENERATION_COMPLETED: 'GRAPH_GENERATION_COMPLETED',
  GRAPH_GENERATION_FAILED: 'GRAPH_GENERATION_FAILED',

  // 그래프 요약 관련
  GRAPH_SUMMARY_COMPLETED: 'GRAPH_SUMMARY_COMPLETED',
  GRAPH_SUMMARY_FAILED: 'GRAPH_SUMMARY_FAILED',

  // 대화 추가 관련
  ADD_CONVERSATION_COMPLETED: 'ADD_CONVERSATION_COMPLETED',
  ADD_CONVERSATION_FAILED: 'ADD_CONVERSATION_FAILED',
} as const;